### ISSUE TITLE
#23 Implement a dashboard

### ISSUE THREAD

**Issue by jonatannapolesoliveira** [jonasnapoles/test-blog#23]
**Implement a dashboard**

- should show all user events

**Comment by jonatannapolesoliveira** [comment]
- Should show the id, title, participants and actions with edit and delete button .

**Comment by jonatannapolesoliveira** [comment]
**BUG**

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.user_id' in 'where clause' (SQL: select * from `users` where `users`.`user_id` = 1 and `users`.`user_id` is not null)

**Comment by jonatannapolesoliveira** [comment]
> **BUG**
> 
> Illuminate\Database\QueryException SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.user_id' in 'where clause' (SQL: select * from `users` where `users`.`user_id` = 1 and `users`.`user_id` is not null)

Should change  model Models/User

`'App\Models\User'`

to

`'App\Models\Event'`

**Comment by jonatannapolesoliveira** [comment]
- Add CRUD: Delete and Update

**Comment by luisapenha** [comment]
Perfectly

**Comment by luisapenha** [comment]
Closed
